# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference_server.proto',
  package='inference_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16inference_server.proto\x12\x10inference_server\":\n\x0cListOfArrays\x12*\n\tarrayList\x18\x01 \x03(\x0b\x32\x17.inference_server.Array\"\'\n\x05\x41rray\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08raw_data\x18\x02 \x01(\x0c\x32^\n\tInference\x12Q\n\tInference\x12\x1e.inference_server.ListOfArrays\x1a\x1e.inference_server.ListOfArrays\"\x00(\x01\x30\x01\x62\x06proto3'
)




_LISTOFARRAYS = _descriptor.Descriptor(
  name='ListOfArrays',
  full_name='inference_server.ListOfArrays',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrayList', full_name='inference_server.ListOfArrays.arrayList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=102,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='inference_server.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='inference_server.Array.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='inference_server.Array.raw_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=143,
)

_LISTOFARRAYS.fields_by_name['arrayList'].message_type = _ARRAY
DESCRIPTOR.message_types_by_name['ListOfArrays'] = _LISTOFARRAYS
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListOfArrays = _reflection.GeneratedProtocolMessageType('ListOfArrays', (_message.Message,), {
  'DESCRIPTOR' : _LISTOFARRAYS,
  '__module__' : 'inference_server_pb2'
  # @@protoc_insertion_point(class_scope:inference_server.ListOfArrays)
  })
_sym_db.RegisterMessage(ListOfArrays)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), {
  'DESCRIPTOR' : _ARRAY,
  '__module__' : 'inference_server_pb2'
  # @@protoc_insertion_point(class_scope:inference_server.Array)
  })
_sym_db.RegisterMessage(Array)



_INFERENCE = _descriptor.ServiceDescriptor(
  name='Inference',
  full_name='inference_server.Inference',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=145,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inference',
    full_name='inference_server.Inference.Inference',
    index=0,
    containing_service=None,
    input_type=_LISTOFARRAYS,
    output_type=_LISTOFARRAYS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFERENCE)

DESCRIPTOR.services_by_name['Inference'] = _INFERENCE

# @@protoc_insertion_point(module_scope)
