#!/bin/bash -l

sudo service ssh start
sudo redir --lport=443 --cport=8443 --caddr=localhost &
cd ~/ml-suite
conda activate ml-suite
source ./overlaybins/setup.sh nimbix
exec jupyter notebook --notebook-dir=notebooks --no-browser --port=8443 --certfile=/etc/JARVICE/cert.pem --NotebookApp.token=

